services:
  mysql-db:
    image: mysql:8.0
    container_name: gic-book-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstoredb
      MYSQL_USER: bookstoreuser
      MYSQL_PASSWORD: bookstorepass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: gic-book-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bookstoredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bookstoreuser
      SPRING_DATASOURCE_PASSWORD: bookstorepass
      SPRING_PROFILES_ACTIVE: development
    restart: on-failure

volumes:
  mysql-data: